var DomainInfoRes = {
	alert_DomainAutoRenew_Title: "{0}: Domain Auto-renew",
	alert_PremiumDnsAutoTurnOn: "Auto-renew is currently turned off for your PremiumDNS. Would you like to turn it on?",
	alert_Site_AlertActionForEmptySelectionMessage: "Select the domain(s) to be modified by this action.",
	alert_Site_AlertActionForEmptySelectionMessage_OnExpiryList: "Select the product(s) to be modified by this action.",
	alert_Site_AutoRenewFailedMessage: "You do not have eligible domains for auto renew.Please try again  with other domains.",
	alert_Site_DomainLockFailedMessage: "You do not have eligible domains for domain lock.Please try again with another domains.",
	alert_Site_SaveDomainLockCheckedSuccessMessage: "Pages updated. Changes are processing. We\u2019ll send you an email once completed.",
	alert_Site_SaveDomainLockNotCheckedSuccessMessage: "Pages updated. Changes are processing.",
	alert_Site_VerifyContactsFailedMessage: "You do not have eligible domains for verification.Please try again with another domains.",
	alert_WgAutoTurnOn: "Auto-renew is currently turned off for your WhoisGuard. Would you like to turn it on?",
	alert_WgPremiumDnsAutoTurnOn: "You're about to turn on auto-renewal for your domain. Would you like to turn on auto-renewal for your domain's WhoisGuard and PremiumDNS services as well?",
	alertText_needSetNameserversAtYourRegistrar: "Please configure the nameservers at your domain registrar.",
	alertText_PremiumDns_ExpiringSoon: "Your PremiumDNS will expire soon.",
	error_Alert_Dynamic_AssociatesDomainAutoRenew: "Oops! Something went wrong. Please try again.",
	error_Alert_FailedToSetEmailTypeMessage: "Failed to set email type",
	error_Alert_LoaderSyncDomainExistMessage: "The refresh process has begun. We\u2019ll let you know when it\u2019s complete.",
	error_Alert_SiteSyncDomainExistMessage: "The refresh process has begun. We\u2019ll let you know when it\u2019s complete.",
	error_Alert_SyncDomainErrorMessage: "Sync domain list is not updated in the queue list",
	error_Contextual_co_ukDomainRegistrarLockAlert: " domains does not support to change Registrar Lock.",
	error_Contextual_DomainAddCategoryAlert: "Please select a category from the dropdown menu.",
	error_Contextual_DomainAddCategoryFailed: "Category created failed.",
	error_Contextual_DomainExpired: "Cannot change ownership or grant permission for this domain because it is expired.",
	error_Contextual_DomainInSale: "Cannot change ownership or grant permission for this domain because it is for sale.",
	error_Contextual_DomainLocked: "Cannot change ownership or grant permission for this domain because it is locked.",
	error_Contextual_DomainNotAvailable: "Domain not in account.",
	error_Contextual_DomainSetContactsFailed: "Failed to change contacts for specified domain. Please try again.",
	error_Contextual_EmailRedirectForwarderBulkRemove: "Failed to remove. Please try again.",
	error_Contextual_EmailRedirectForwarderRemove: "Failed to remove. Please try again.",
	error_Contextual_ForwarderAllowedCharacters: "Digits, letters and \u201C.\u201D, \u201C-\u201D or \u201C_\u201D only.",
	error_Contextual_ForwarderDestinationEmailIsEmpty: "This field can\u2019t be empty",
	error_Contextual_ForwarderNameIsEmpty: "Enter a Forwarder Name",
	error_Contextual_ForwarderNameLength: "Maximum 64 characters.",
	error_Contextual_InvalidNewOwnerValue: "New owner data invalid. Please try again.",
	error_Contextual_InvalidOwner: "Domain owner is invalid or user does not own the domain.",
	error_Contextual_InvalidParameterValue: "Invalid user entry. Please try again.",
	error_Contextual_InvalidUserName: "Please provide a valid username.",
	error_Contextual_IPSTagRequired: "A valid IPS tag is required.",
	error_Contextual_LoaderNoDomainsToSync: "Sorry, we were unable to initiate the refresh process. Please try again.",
	error_Contextual_ManagerAndDominOwnerSameName: "Domain owner cannot be added as domain manager.",
	error_Contextual_NotDomainOwner: "You do not own this domain.",
	error_Contextual_PasswordRequired: "Account password required.",
	error_Contextual_PushAcceptDetailsInvalid: "Ownership change verification code is invalid or invitation has expired.",
	error_Contextual_PushDomainCompletionSendMailFailed: "Domain was pushed successfully, but send mail after push failed",
	error_Contextual_PushDomainDbUpdateFailedAfterInvitationSentSuccessfully: "Change of ownership invitation has been sent.",
	error_Contextual_PushDomainDbUpdateFailedAfterPushSuccess: "Ownership change completed successfully.",
	error_Contextual_PushDomainDestinationUserInvalid: "The user who has accepted this invitation is not the same user to whom it was sent.",
	error_Contextual_PushDomainNewUserInvalid: "Intended recipient does not have a valid user account.",
	error_Contextual_PushDomainToUserDbFailed: "An error occurred during change of ownership. Please try again.",
	error_Contextual_PushDomainWhoisAddressInvalid: "Ownership change failed because recipient's address is invalid.",
	error_Contextual_PushDominOwnerSameName: "Domain ownership cannot be changed to current owner.",
	error_Contextual_PushInvalidAuthCode: "Change of ownership process aborted due to invalid verification code.",
	error_Contextual_PushInvalidStatus: "Invitation is in invalid status for processing.",
	error_Contextual_PushInvitationExpired: "Change of ownership invitation has expired.",
	error_Contextual_PushPendingInvitationExists: "There is already a pending ownership change for this domain.",
	error_Contextual_PushSendInvitationMailFailed: "Change of ownership invitation was not sent. Resend invitation.",
	error_Contextual_PushWarningWGEnabledContactsNotChanged: "Domain ownership change completed with WhoisGuard enabled.",
	error_Contextual_SiteNoDomainsToSync: "Sorry, we were unable to initiate the refresh process. Please try again.",
	Error_Dynamic_SaveNameServer: "Failed to change nameserver type.",
	error_Site_AddEditForwarder: "Forwarder/Catch-All could not be configured or updated due to errors. Please review the errors within the form and try again.",
	error_Site_co_ukDomainRegistrarLockAlert: " domains does not support to change Registrar Lock.",
	error_Site_DomainExpired: "Cannot change ownership or grant permission for this domain because it is expired.",
	error_Site_DomainInSale: "Cannot change ownership or grant permission for this domain because it is for sale.",
	error_Site_DomainIsOnSale: "Cannot change ownership or grant permission for this domain because it is for sale",
	error_Site_DomainLocked: "Cannot change ownership or grant permission for this domain because it is locked.",
	error_Site_DomainLockOffMessage: "Failed to turn OFF domain lock.Please try again.",
	error_Site_DomainLockOnMessage: "Failed to turn ON domain lock.Please try again.",
	error_Site_DomainNameExpired: "This domain name is expired.",
	error_Site_DomainNameNotAvailable: "This domain name is not available.",
	error_Site_DomainNotAvailable: "This domain name is not in this Namecheap user account.",
	error_Site_DomainRightsDestinationUserInvalid: "The user who has accepted this invitation is not the same user to whom it was sent.",
	error_Site_DomainSetContactsFailed: "Contacts have not been changed for this domain. Please try again.",
	error_Site_FreeDnsAuthEmailRetrieveFailed: "Error while fetching email address list",
	error_Site_FreeDnsAuthEmailSavedErrorMessage: "Error while updating new authorization email",
	error_Site_InvalidAuthCode: "Invalid verification code. Please re-enter.",
	error_Site_InvalidAuthCode_CodeExpired: "This verification code has expired.",
	error_Site_InvalidAuthCode_ReqeustCancelled: "This invitation has been cancelled by the domain owner.",
	error_Site_InvalidAuthCode_ReqeustDeniedAlready: "This invitation has already been declined.",
	error_Site_InvalidAuthCode_ReqeustProcessedAlready: "This invitation is already being processed.",
	error_Site_InvalidAuthorizationCode: "This verification code is invalid. Please try again.",
	error_Site_InvalidNewOwnerValue: "The user who is attempting to accept this invitation is not the same user to whom it was sent.",
	error_Site_InvalidOwner: "This domain has undergone a change of ownership.",
	error_Site_InvalidParameterValue: "Invalid entry. Please try again.",
	error_Site_InvalidStatus: "Status is invalid",
	error_Site_NotDomainOwner: "You do not own this domain.",
	error_Site_OWNER_TARGET_SAMEUSER: "Cannot add domain owner as Domain Manager",
	error_Site_ParkingPageTurnOn: "Parking Page could not be turned on. Please try again later.",
	error_Site_PasswordErrorMessage: "You've entered an incorrect password. Please try again.",
	error_Site_PasswordRequired: "Account password is required.",
	error_Site_Permission_AddErrorMessage: "An internal error has occurred. Please try again.",
	error_Site_Permission_AlreadyAdded: "This domain manager already has access. Visit the Domain Managers section to edit manager's permissions.",
	error_Site_Permission_AlreadyInitiated: "This user already has access permissions.",
	error_Site_Permission_InavalidUserName: "This username does not exist in our system. Please try again.",
	error_Site_PushAcceptDetailsInvalid: "Ownership change verification code is invalid or invitation has expired.",
	error_Site_PushDomainCompletionSendMailFailed: "Domain was pushed successfully, but send mail after push failed",
	error_Site_PushDomainDbUpdateFailedAfterInvitationSentSuccessfully: "Change of ownership invitation has been sent.",
	error_Site_PushDomainDbUpdateFailedAfterPushSuccess: "Ownership change completed successfully.",
	error_Site_PushDomainDestinationUserInvalid: "The user who has accepted this invitation is not the same user to whom it was sent.",
	error_Site_PushDomainNewUserInvalid: "Intended recipient does not have a valid user account.",
	error_Site_PushDomainToUserDbFailed: "An error occurred during change of ownership. Please try again.",
	error_Site_PushDomainWhoisAddressInvalid: "Ownership change failed because recipient's address is invalid.",
	error_Site_PushInvalidAuthCode: "Change of ownership process aborted due to invalid verification code.",
	error_Site_PushInvalidStatus: "This invitation is in an invalid status for processing. Please review and try again.",
	error_Site_PushInvitationExpired: "Change of ownership invitation has expired.",
	error_Site_PushPendingInvitationExists: "There is already a pending ownership change for this domain.",
	error_Site_PushSendInvitationMailFailed: "Change of ownership invitation was not sent. Resend invitation.",
	error_Site_PushWarningWGEnabledContactsNotChanged: "Domain ownership change completed with WhoisGuard enabled.",
	error_Site_RedirectDomain: "Redirect domain failed",
	error_Site_ResendEmailErrorMessage: "Failed to send. Please try again.",
	error_Site_SaveAddCategoryMessage: "Failed to assign {Category} to the selected domains. Please try again.",
	error_Site_SaveAutoRenewMessage: "Failed to update. Please try again.",
	error_Site_SendingMailFailed: "An internal error occurred during email send. Please try again.",
	error_Site_SetToFreeDns: "Email forwarding is not working because your domain is not using Namecheap DNS.",
	error_Site_SyncMessage: "Too bad. We were unable to complete the refresh process. Please try again.",
	error_Site_UserNotAuthorized: "User not authorized.",
	error_TurnedOffParkingPage: "Parking Page could not be turned off. Please try again later.",
	failure_Alert_Category_Chosen: "Failed.",
	failure_Alert_Domain_Expired: "Domain is expired.Failed to turn WhoisGuard {[whoisAction]}.",
	failure_Alert_DomainAutoRenewDisable: "Failed to turn domain auto-renew off",
	failure_Alert_DomainAutoRenewEnable: "Failed to turn domain auto-renew on",
	failure_Alert_HostingAutoRenewDisable: "It was not possible to disable the Hosting AutoRenew.",
	failure_Alert_HostingAutoRenewEnable: "It was not possible to enable the Hosting AutoRenew.",
	failure_Alert_PremiumDnsAutoRenewEnable: "Failed to turn PremiumDNS auto-renew on",
	failure_Alert_RegistrantResendNotification: "Failed to send Email.",
	failure_Alert_WhoisGuardAutoRenewDisable: "Failed to turn WhoisGuard auto-renew off",
	failure_Alert_WhoisGuardAutoRenewEnable: "Failed to turn WhoisGuard auto-renew on",
	failure_Alert_WhoisGuardChangeForwardedEmail: "Sorry, we weren\u2019t able to update your Forwarding Email Address. Please try again.",
	failure_Alert_WhoisGuardOnOff: "Failed to turn WhoisGuard {[whoisAction]}.",
	failure_Alert_WhoisGuardRefreshDuration: "Sorry, we weren\u2019t able to refresh the WhoisGuard Email Auto Update timeframe. Please try again.",
	failure_Alert_WhoisGuardRefreshEmail: "Failed to refresh \u201CReceive Emails At\u201D address.",
	failure_AlertPremiumDnsAutoRenewDisable: "Failed to turn PremiumDNS auto-renew off",
	introText_PremiumDns: "Enable PremiumDNS protection in order to switch your domain to our PremiumDNS platform. With our PremiumDNS platform, you get 100% DNS uptime and DDoS protection at the DNS level.",
	label_Also_Being_Pushed: "Associated Services",
	label_AuthCode: "Auth Code",
	label_Category: "Category",
	label_DomainLockOptions: "Domain Lock",
	label_Permission_AccountPassword: "Namecheap Password",
	label_Permission_ManagerPermissions: "Manager's Access",
	label_Permission_NewManager: "New Manager",
	label_PushNewOwner: "New Owner",
	label_RegistrantContact: "Registrant Contact",
	label_TransferDomain: "Why do you transfer your domains out of Namecheap?",
	notification_Contextual_PushInitiated: "Change of ownership initiated.",
	notification_SomeProductsBlocked: "Some products are blocked",
	prompt_Content_AutoRenew_PM1: "You're about to turn on auto-renewal for your domain. Would you like to turn on auto-renewal for your domain's WhoisGuard and PremiumDNS services as well?",
	prompt_Content_AutoRenew_PM2: "You're about to turn on auto-renewal for your domain. Would you like to turn on auto-renewal for your domain's WhoisGuard service as well?",
	prompt_Content_AutoRenew_PM3: "You're about to turn on auto-renewal for your domain. Would you like to turn on auto-renewal for your domain's PremiumDNS service as well?",
	prompt_Content_AutoRenew_PM4: "You\u2019re about to turn off auto-renewal for your domain. Please note that this action will also disable auto-renewal for WhoisGuard and PremiumDNS services associated with the domain. Would you like to proceed?",
	prompt_Content_AutoRenew_PM5: "You\u2019re about to turn off auto-renewal for your domain. Please note that this action will also disable auto-renewal for WhoisGuard service associated with the domain. Would you like to proceed?",
	prompt_Content_AutoRenew_PM6: "You\u2019re about to turn off auto-renewal for your domain. Please note that this action will also disable auto-renewal for PremiumDNS service associated with the domain. Would you like to proceed?",
	prompt_Content_AutoRenew_PM7: "You're about to turn on auto-renewal for your domain's WhoisGuard service. Please note that this action will also enable auto-renewal for your domain. Would you like to proceed?",
	prompt_Content_AutoRenew_PM8: "You're about to turn on auto-renewal for your domain's PremiumDNS service. Please note that this action will also enable auto-renewal for your domain. Would you like to proceed?",
	prompt_Titel_AutoRenew_PDNSTurnOn: "Turn On PremiumDNS Auto-Renewal",
	prompt_Titel_AutoRenew_TurnOff: "Turn Off Domain Auto-Renewal",
	prompt_Titel_AutoRenew_TurnOn: "Turn On Domain Auto-Renewal",
	prompt_Titel_AutoRenew_WGTurnOn: "Turn On WhoisGuard Auto-Renewal",
	site_Alert_ForUsingFreeDns: "Email forwarding is not working because your domain is not using Namecheap DNS.",
	staic_NotConfigured: "Not Configured",
	staic_Products: "Products",
	static_Actions: "Actions",
	static_Active: "ACTIVE",
	static_Add_MailBox: "ADD MAILBOX",
	static_AddCategory: "Add Category",
	static_AddCategoryIntroduction: "You can create different categories for your domains. Selected category will be applied to all the selected domains.",
	static_AdditionalDomainRedirect: "additional subdomain redirect",
	static_AddNameServers: "ADD NAMESERVER",
	static_AdminstratorContacts: "Administrative Contacts",
	static_AdvancedDNS: "Advanced DNS",
	static_AgreeConditionSwitchDns: "I understand that setting up Email Redirect will affect my existing services and they may stop working.",
	static_AgreeConditionSwitchDnsError: "To continue, you must agree to the DNS change.",
	static_Alert: "ALERT",
	static_AllProductsList: "All Products List",
	static_AllServices: "All Services",
	static_AuthcodeOnly_Intro: "From here, you can transfer your domain name out from Namecheap to another registrar. To transfer out, you will need to get an Auth Code. After you place the request here, we'll send your Auth Code to the registrant email address specified for this domain. It may take up to 5 days for the transfer to be completed. \r\nTo learn more about Auth Codes, <a target=\"_blank\"  href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/1421/84/my-hosting-provider-is-asking-for-my-eppauthorization-code-is-it-safe-to-provide-it\">consult this article.</a>",
	static_AuthCodeSelection: "I want to receive AuthCode for the selected domains",
	static_AutoRenew: "Auto-Renew",
	static_AutoRenewDomain: "Auto-renew Domain Name every year",
	static_AutoRenewIntroductionMultiple: "Using this option you can turn auto-renewal ON or OFF for the selected services. For the items with auto-renewal enabled, we will try to renew the service/s using funds (if available), or the card info you\u2019ve provided. For more info ",
	static_AutoRenewIntroductionSingle: "This option allows you to turn auto-renewal ON or OFF for the selected service. If autorenewal is enabled for your domain, we will try to renew the service using funds (if available) or the card info you\u2019ve provided. For more info",
	static_AutoRenewModalTitle: "Auto-Renewal Preferences",
	static_AutoRenewOptions: "AutoRenew Options",
	static_AutoRenewWhoisguard: "Auto-renew WhoisGuard every year",
	static_BillingContacts: "Billing Contacts",
	static_Blocked: "Blocked",
	static_BulkEmailRedirectIntroduction: "Email Forwarding is a free service that allows you to receive emails at your personal you@yourdomain.com email address by redirecting them to another email account. The service is for incoming mail only. To be able to send emails from your personal email address, please consider upgrading to Private Email service.",
	static_BulkModifications: "Bulk Modifications",
	static_BulkModificationsPageIntro: "Bulk modifications list shows the list of actions that performed by user on domains.User can hide,cancel and show the details of domains.The list shows the status,submitted details  of the domain to the user.",
	static_BulkModifyList: "Multiple Modifications List",
	static_BuyNow: "Buy Now",
	static_CancelPushConfirmation: "Are you sure you want to cancel this change of ownership invitation?",
	static_Category: "Category",
	static_Change: "Change",
	static_ChangeForwardedEmail: "Select the email address to which all correspondence received at \u201CWhoisGuard Email Address\u201D will be forwarded to",
	static_ChangeIPSTag: "Change IPS Tag",
	static_ChangeIPSTag_Intro: "Every registrar who provides .uk domain names is identified by an IPS Tag. To transfer out of Namecheap, you must change the IPS Tag associated with your domain. Enter your new registrar's IPS Tag here. It may take 24\u201348 hours to process this change. Once the change is confirmed, your domain will be transferred immediately.",
	static_ChangeOwnership: "Change Ownership",
	static_CompanyAddress: "Domain is registered on behalf of a company",
	static_CompanyAddressBulkEdit: "Domains are registered on behalf of a company",
	static_Configured: "Configured",
	static_ContactInfo: "I wish to be contacted in the future.",
	static_Contextual_FreeDNS: "This domain is using FreeDNS",
	static_Contextual_NoActiveManger: "No managers listed.",
	static_Contextual_Subdomains_FreeDNS: "You have {0} subdomains using Namecheap FreeDNS.  <a target='_blank' href=\"\">View them here  \u2192 </a>",
	static_ControlPanel: "Control Panel",
	static_CurrentIPSTag: "Current IPS Tag",
	static_Days: "days.",
	static_Description: "Description",
	static_DNSHostRecords: "DNS / Host Records",
	static_Domain: "Domain",
	static_DomainAvailable_forSale: "Available for sale",
	static_DomainContacts: "Domain Contacts",
	static_DomainControlPanel_Intro: "From this page, you can designate individuals to act as managers for your domain, choose which settings your managers have permission to edit, move ownership of your domains to other Namecheap accounts, or transfer a domain out of Namecheap to another registrar.",
	static_DomainInGrace: "This domain is in Grace period",
	static_DomainList: "Domain List",
	static_DomainLock: "Domain Lock",
	static_DomainLockAuthcode_Intro: "From here, you can transfer your domain name out from Namecheap to another registrar. To transfer out, you will need to make sure that Domain Lock is turned OFF and get an Auth Code. After you place the request here, we'll send your Auth Code to the registrant email address specified for this domain. It may take up to 5 days for the transfer to be completed.\r\nFor more information on Domain Lock,<a target=\"_blank\"  href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/565/8/what-is-registrar-lock\"> view this Knowledgebase article.</a>To learn more about Auth Codes,<a target=\"_blank\"  href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/1421/84/my-hosting-provider-is-asking-for-my-eppauthorization-code-is-it-safe-to-provide-it\"> consult this article.</a>",
	static_DomainLockIntroduction: "In order to transfer a domain out of Namecheap, it should be unlocked and an EPP/authentication code should be requested. If your selection includes unlocked and locked domains, only locked domains will be unlocked. Unlocked domains will remain unlocked. EPP/authentication codes will be sent for applicable domains only. {0} domains can be updated.",
	static_DomainLockIntroductionSingle: "In order to transfer a domain out of Namecheap, it should be unlocked and an EPP/authentication code should be requested. If your selection includes unlocked and locked domains, only locked domains will be unlocked. Unlocked domains will remain unlocked. EPP/authentication codes will be sent for applicable domains only. {0} domain can be updated.",
	static_DomainLockModalTitle: "Transfer Out",
	static_DomainLockOnly_Intro: "From here, you can transfer your domain name out from Namecheap to another registrar. To transfer out, you will need to make sure that Domain Lock is turned OFF. It may take up to 5 days for the transfer to be completed. \r\nFor more information on Domain Lock,<a target=\"_blank\"  href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/565/8/what-is-registrar-lock\">view this Knowledgebase article.</a>",
	static_DomainRedirect: "Domain Redirect",
	static_DoneButton: "Done",
	static_DropDown_Permission_All: "Give manager full access",
	static_DropDown_Permission_Some: "Give manager some permissions",
	static_EmailForwarders: "Email Forwarders",
	Static_EmailNotificationInfo: "Notify me via email once the action is completed.",
	static_EmailRedirect: "Email Redirect",
	static_EmailRedirectIntro: "Email Redirect is a free service that allows you to receive emails at your personal you@yourdomain.com email address by redirecting them to another email account.",
	static_EmailRedirectIntroduction: "Email Forwarding is a free service that allows you to receive emails at your personal you@yourdomain.com email address by redirecting them to another email account. This service is for incoming mail only. To send emails from your personal email address, consider upgrading to [Private Email] service.",
	static_EmailRedirectListMessage: "You haven\u2019t configured any forwarder yet.",
	static_EmailRedirectListTitle: "{{Used}} of {{Total}} Email Forwarders in Use",
	static_EmailRedirectTitle: " : Manage Email Redirect",
	static_Enom_IPSTag_Comment: "New IPS tag for domain transfer.",
	static_Expired: "EXPIRED",
	static_FailuremessagetoUser: "The domain owner cannot be added as a domain manager.",
	static_Fax: "fax:",
	static_ForwardEmailsTo: "Forward Emails To",
	static_ForwardTo: "Forward to",
	static_FreeDns: "Namecheap FreeDNS",
	static_GetAuthCode: "AUTH CODE",
	static_GetAuthCode_Intro: "The Auth Code is a unique code assigned to each domain name at the time of registration. ICANN requires your Auth Code in order to transfer your domain to another registrar. Use this window to request your code; we'll email it to the registrant email address specified for this domain.",
	static_GetAuthentication_Code: "Get Auth Code",
	static_Grace: "GRACE",
	static_HideDetails: "HIDE DETAILS",
	static_Info: "info",
	static_InTransfer: "In Transfer",
	static_Intro_DomainRedirectIfCustomNameserver: "You can create redirects via your DNS provider or your Namecheap account. To perform this function from your account, you must first change your nameservers to Namecheap default. <a target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/782/10\">Learn How &rarr;</a>",
	static_Intro_DomainRedirectIfSharedHosting: "Your domain is using Namecheap Hosting Nameservers (DNS), which means you can set a domain redirect within cPanel.\r\n\r\nPlease refer to this <a target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/9257/29/how-to-create-a-sitedomain-redirect-in-cpanel\">Knowledgebase article &rarr;</a> for detailed instructions. \r\n\r\nAlternatively, you can set your domain to use our default Nameservers (DNS) to set up Domain Redirect in your Namecheap account. However, hosting services will stop working in this case.",
	static_Intro_EmailRedirectIfCustomNameserver: "You can create redirects via your DNS provider or your Namecheap account. To perform this function from your account, you must first change your nameservers to Namecheap default. <a target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/782/10\">Learn How &rarr;</a>",
	static_Intro_EmailRedirectIfPrivateEmail: "Email Redirect is a free service that allows you to receive emails at your personal you@yourdomain.com email address by redirecting them to another email account. If you are using Private Email, use its interface to set up a redirect.<a target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/1396/2214/how-to-setup-forwarding-in-namecheap-private-email\">Learn More &rarr;</a>",
	static_Intro_EmailRedirectIfPrivateEmailWithNC: "You can create redirects from cPanel.",
	static_Intro_EmailRedirectIfSharedHosting: "You can create redirects via cPanel or your Namecheap account. To perform this function from your account, you must first change your nameservers to Namecheap default. <a target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/782/10\">Learn How &rarr;</a>",
	static_IPSTag: "New IPS Tag",
	static_IPSTag_Intro: "From here, you can transfer your domain name out from Namecheap to another registrar. To transfer out, you will need to change your IPS Tag. Once the IPS Tag is changed, your domain will be transferred immediately.",
	static_IsMultidomain: "MULTIDOMAIN",
	static_IsProrated: "Prorated price for remaining months",
	static_IsTrial: "TRIAL",
	static_LastRefreshedOn: "Last refreshed on",
	static_LessThanSixtydays_EPPCodeWarning: "IMPORTANT: We strongly advise against providing your Authorization Code to ANYONE, including your host. Making it available to others is a massive security breach. If someone is asking to \"authenticate\" your domain ownership by asking for your Authorization Code, they may have questionable or negative intentions.\r\nBear in mind that domains that are less than 60 days old are not eligible for transfer.",
	static_Loading_Category_Chosen: "Allotting Category.",
	static_Loading_Category_Creation: "Creating New Category.",
	static_Loading_Category_Removal: "Removing Category",
	static_Loading_DomainAutoRenewEnableDisable: "Enable/Disable Domain Auto-Renew request is being processed.",
	static_Loading_PremiumDnsRenewEnableDisable: "Enable/Disable PremiumDNS Auto-Renew request is being processed.",
	static_Loading_RegistrantResendNotification: "Resending Email. Please wait..",
	static_Loading_WhoisGuardAutoRenewEnableDisable: "Enable/Disable Whoisguard Auto-Renew request is being processed.",
	static_Loading_WhoisGuardOnOff: "Turning {[whoisAction]} WhoisGuard.",
	static_Loading_WhoisGuardRefreshEmail: "Refreshing \"Receive Emails At\" address.",
	static_Lock: "Lock",
	static_LockAll: "Lock All",
	static_ManageDomainAndServices: "Manage Domain & Services",
	static_ManageUpdates: "Select the periodicity of WhoisGuard Email address updates",
	static_Managing: "Managing",
	static_Modal_Intro_AddEditCatchAll: "The input email address will \"catch\" any mail sent to an invalid email address for your domain. Configuring a catch-all address can help you avoid losing emails due to misspellings.",
	static_Modal_Intro_AddEditForwarder: "Email forwarder allows you to send a copy of an email from one email address to another email address automatically. Adestination email is the email address where mail will be forwarded to.",
	static_Modal_Title_AddCatchAll: "Add Catch-All",
	static_Modal_Title_AddForwarder: "Add Forwarder",
	static_Modal_Title_EditCatchAll: "Edit Catch-All",
	static_Modal_Title_EditForwarder: "Edit Forwarder",
	static_Modal_Title_RemoveForwarder: "Remove Email Forwarders",
	static_MultiRemovePromptIntro: "Are you sure want to delete?",
	static_NeedsToBeVerified: "Needs to be verified",
	static_New: "New",
	static_OnSale: "For Sale",
	static_Optional: "Optional",
	static_Other: "Other",
	static_OtherDomainSettings: "Other Domain Settings",
	static_ParkingPage: "Parking Page",
	static_ParkingPage_Disabled: "Disabled",
	static_ParkingPageConfirmCheckBoxText: "I understated that setting up Parking Page will affect my existing services and they may stop working.",
	static_ParkingPageInfoAboutDnsUpdate: "If you have recently updated your domain\u2019s DNS settings, please allow up to 24 hours for changes to take effect. You may also need to clear your browser\u2019s cache and/or delete cookies and try again.",
	static_ParkingPageInfoAboutServiceUpdate: "If you have recently updated your domain service(s), please allow up to 24 hours for changes to take effect. You may also need to clear your browser\u2019s cache and/or delete cookies and try again.",
	static_ParkingPageOverview: "The Parking Page can be displayed when you have registered your domain name but do not yet have your website ready.",
	static_ParkingPageReasonsToUseIt: "Users visiting your domain will see your customized message telling them that they have reached the correct site and it is currently under construction.",
	static_Permission_Desc: "Here you have the opportunity to select which settings your new domain manager will have access to edit. Giving your manager access to make changes on your behalf can save you time and work, but keep in mind: For security reasons, you might not want to share access to all settings. Enter your account password in the appropriate field to confirm that you wish to share access to these settings with your new domain manager.",
	static_Permissions: "Share Access",
	static_Permissions_Intro: "Change access rights for the individuals you have designated to act as domain managers. You can also designate a new manager, using that person's email address or Namecheap username.",
	static_PersonalContacts: "Personal Domain Contacts",
	static_PersonalDomainContactIntro: "Each domain registered must include contact details. These are stored in a public WHOIS database so that the domain owner can be contacted, as needed. We call them \u201CDomain Contacts\u201D (aka. Whois Contacts). Customers have the ability to edit them.",
	static_PersonalDomainContactKBLink: "Learn more about personal domain contacts",
	static_PhoneExtensionText: "Add phone extension",
	static_Premium: "Premium",
	static_PremiumDNS: "PremiumDNS",
	static_Pricing: "Pricing",
	static_PrivateEmail_Intro: "Our private cloud is a secure, reliable solution for your email needs.All of our Private Email plans come with a fast, lightweight webmail interface for managing your email, contacts and calendar.",
	static_PrivateEmailIntro: "As you are using Private Email, use its interface to set up a redirect.",
	static_Protection: "PROTECTION",
	static_PublicAddress: "Public Address",
	static_PublicContacts: "Public Domain Contacts",
	static_PubliContactIntro: "WhoisGuard is a service that allows customers to keep their domain contacts confidential from spammers, marketing firms and online fraudsters. When purchased, the WhoisGuard subscription is permanently assigned to a domain and stays attached to it as long as the fee is paid.",
	static_Push: "Change Ownership",
	static_Push_Intro: "With a change of ownership, you fully relinquish ownership of the domain (along with some associated services) and designate a new owner. If the new owner doesn't have a Namecheap account yet, she or he will have the option to create one.",
	static_PushPopup_Intro: "Use this form to indicate which contact info should be listed for the domain after the change of ownership. Some verification is likely to be required if you choose to use new contacts. We recommend you choose to use new contacts, in order to avoid confusion and verification difficulties in the future. Please enter your account password as confirmation of your identity.",
	static_PushPopupTitle: "Change Ownership",
	static_ReadyForSale: "You can sell this domain",
	static_ReceiveEmailsAt: "Receive Emails At",
	static_ReceiveEmailsAtIntro: "Emails to WhoisGuard Email Address are forwarded here.",
	static_ReceivingAt: "Receiving at",
	static_ReceivingMailInfo: "This email will be automatically refreshed in the selected period",
	static_RefreshesAutomaticalyEvery: "Refreshes automatically every",
	static_RegisterDomainLink: "Register your domain now!",
	static_Registrant_Contact1: "Use new owner's contacts",
	static_Registrant_Contact2: "Use current contacts",
	static_RegistrantContacts: "Registrant Contacts",
	static_Registrar: "Registrar",
	static_RemoveManagerConfirmation: "Are you sure you want to remove this Domain Manager?",
	static_RenewExpiring: "Renew Expiring",
	static_RightsAndTransfer: "Sharing & Transfers",
	static_SaveChangeButton: "Save Change",
	static_SearchIsEmpty: "Search Is Empty",
	static_SelectReason: "Select Reason",
	static_SellDomain: "Sell Domain",
	static_SetupEmailRedirectIntro: "Before you set up Email Redirect, your domain should be pointed to our default DNS.",
	static_ShowDetails: "SHOW DETAILS",
	static_Site_LoaderSyncProcessMessage: "The refresh process has begun. We\u2019ll let you know when it\u2019s complete.",
	static_Site_NoRecordsToManager: "No access rights have been granted to this manager.",
	static_Site_SiteSyncProcessMessage: "The refresh process has begun. We\u2019ll let you know when it\u2019s complete.",
	static_Status: "Status",
	static_Support: "Support",
	static_SyncRefresh: "Refresh",
	static_Technical: "Technical",
	static_TechnicalContacts: "Technical Contacts",
	static_Tel: "tel:",
	static_Tooltip_CatchAllForwarder: "Configuring a catch-all address can help you avoid losing emails due to misspellings.",
	static_TransferIn: "Transfer In",
	static_TransferIn_Intro: "<p>Would you like to take advantage of our domain management tools and apps, maintain all your account details from one place, access our 24/7/365 Live Chat support, and more? Use this section to initiate and manage the transfer process.</p>",
	static_TransferOut: "Transfer Out",
	static_TransferOut_Intro: "From here, you can transfer your domain name out from Namecheap to another registrar. To transfer out, you will need to make sure that Domain Lock is turned OFF and get an Auth Code. After you place the request here, we'll send your Auth Code to the registrant email address specified for this domain. It may take up to 5 days for the transfer to be completed.\r\nFor more information on Domain Lock, <a target=\"_blank\"  href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/565/8/what-is-registrar-lock\">view this Knowledgebase article.</a>\r\nTo learn more about Auth Codes, <a target=\"_blank\"  href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/1421/84/my-hosting-provider-is-asking-for-my-eppauthorization-code-is-it-safe-to-provide-it\">consult this article. </a>",
	static_Trial: "Trial",
	static_TurningOffParkingPageLoading: "Turning off Parking Page.",
	static_TurningOnParkingPageLoading: "Turning on Parking Page",
	static_TurnOff: "Turn Off",
	static_TurnOn: "Turn On",
	static_TurnOnParkingPage: "Turn On Parking Page",
	static_UnLockAll: "Unlock All",
	static_UnverifiedContacts: "Unverified Contacts",
	static_UpdateNameservers: "Update Nameservers",
	static_UseForAdminContact: "Use for Administrative Contacts",
	static_UseForBillingContact: "Use for Billing Contacts",
	static_UseForTechContact: "Use for Technical Contacts",
	static_UsingAnotherEmailServiceIntro: "Another email service is in use. If you proceed with the changes, existing services associated with the domain may stop working due to DNS propagation time, which usually takes 24-48 hours.",
	static_UsingHostingAccountIntro: "As you are using email within your hosting account, use the control panel to set up Email Redirect.",
	static_UsingHostingDNSIntro: "As you are using hosting DNS, you need to use cPanel to set up an Email Redirect.",
	static_UsingThirdPartyDnsIntro: "You are using third-party DNS. If you proceed with these changes and don\u2019t change settings to ours, any existing services associated with the domain may stop working.",
	static_Validity: "Validity",
	static_Verified: "Verified",
	static_VerifyContacts: "Verify Contacts",
	static_VerifyContactsIntroductionMultiple: "Email verification is required to confirm your domain ownership. The email will contain a link you need to click on, to verify your email. You need to verify contacts for {0} domains. For more info ",
	static_VerifyContactsIntroductionSingle: "Email verification is required to confirm your domain ownership. The email will contain a link you need to click on, to verify your  mail.  For more info",
	static_VerifyContactsNeed: "Lorem ipsum dolor sit amet, <strong>{0} domains</strong> consectetur adipiscing elit.\r\n                        Phasellus pharetra non sapien et lobortis. Praesent in pulvinar tortor, ac porta metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos",
	static_ViewAllDomains: "View all domains",
	static_Whoisguard: "WhoisGuard",
	static_WhoisGuardAddress: "WhoisGuard Address",
	static_WhoisGuardAddressIntro: "Shown in place of your address in public Whois.",
	static_WhoisguardIsOff: "WhoisGuard protection is OFF",
	static_WhoisguardIsOn: "WhoisGuard protection is ON",
	static_WhoisguardNeverTurnedOn: "WhoisGuard protection has never been turned ON",
	static_WhyTransferOutNameCheap: "Why are you transferring your domain out of Namecheap?",
	static_WishToBeContactedInFuture: "It\u2019s okay to contact me in future to follow up on this case.",
	static_WithAnotherRegistrar: "WITH ANOTHER REGISTRAR",
	success_Alert_AutoRenewDisableForDomainWithMinimalAutorenewDays: "We strongly recommend you enable auto-renew, as renewal is required before the expiration date for some domains.",
	success_Alert_Category_Chosen: "Success.",
	success_Alert_Category_Creation: "Successfully Created.",
	success_Alert_Category_Removal: "Successfully Removed.",
	success_Alert_DomainAutoRenewDisable: "Domain Auto-Renew was disabled with success.",
	success_Alert_DomainAutoRenewEnable: "Domain Auto-Renew was enabled with success.",
	success_Alert_Dynamic_AssociatesDomainAutoRenew: "All good! Request processed successfully.",
	success_Alert_HostingAutoRenewDisable: "Hosting Auto-Renew was disabled with success.",
	success_Alert_HostingAutoRenewEnable: "Hosting Auto-Renew was enabled with success.",
	success_Alert_LoaderSyncDomainComplatedMessage: "Good news! Refresh process is complete.",
	success_Alert_LoaderSyncDomainSuccessMessage: "The refresh process has begun. We\u2019ll let you know when it\u2019s complete.",
	success_Alert_PremiumDnsAutoRenewDisable: "PremiumDNS Auto-Renew was disabled with success.",
	success_Alert_PremiumDnsAutoRenewEnable: "PremiumDNS Auto-Renew was enabled with success.",
	success_Alert_PremiumDnsOff: "DNS server update may take up to 48 hours to take effect.",
	success_Alert_PremiumDnsOn: "DNS server update may take up to 48 hours to take effect.",
	success_Alert_RegistrantResendNotification: "Email was sent successfully.",
	success_Alert_SiteSyncDomainComplatedMessage: "Good news! Refresh process is complete.",
	success_Alert_SiteSyncDomainSuccessMessage: "The refresh process has begun. We\u2019ll let you know when it\u2019s complete.",
	success_Alert_WhoisGuardAutoRenewDisable: "Whoisguard Auto-Renew was disabled with success.",
	success_Alert_WhoisGuardAutoRenewEnable: "Whoisguard Auto-Renew was enabled with success.",
	success_Alert_WhoisGuardChangeForwardedEmail: "Forwarding Email Address has been updated.",
	success_Alert_WhoisGuardOff: "WhoisGuard has been turned OFF.",
	success_Alert_WhoisGuardOn: "WhoisGuard has been turned ON.",
	success_Alert_WhoisGuardRefreshDuration: "WhoisGuard Email Auto Update timeframe has been refreshed.",
	success_Alert_WhoisGuardRefreshEmail: "\"Receive Emails At\u201D address has been refreshed.",
	success_Contextual_AddCatchAll: "Catch-All Forwarder configured.",
	success_Contextual_AddForwarder: "{Forwarder} configured.",
	success_Contextual_DomainLocked: "Domain locked successfully.",
	success_Contextual_DomainUnLocked: "Domain unlocked successfully.",
	success_Contextual_EditCatchAll: "Catch-All Forwarder edited.",
	success_Contextual_EditForwarder: "{Forwarder} edited.",
	success_Contextual_EmailRedirectForwarderBulkRemove: "Successfully removed!",
	success_Contextual_EmailRedirectForwarderRemove: "{Forwarder} removed.",
	success_Contextual_IPSTagChanged: "IPS Tag changed. Transfer in progress.",
	success_Contextual_ParkingPageTurnOnConfirmation: "Please confirm that you agree to this update.",
	success_Contextual_UpdatePushPendingStatus: "Ownership change pending approval.",
	success_Dynamic_updateNameServers: "DNS server update successful. Please note that these changes may take up to 48 hours.",
	success_Site_DeleteRightsStatus: "Access rights have been removed for the designated manager.",
	success_Site_DomainLocked: "Domain locked successfully.",
	success_Site_DomainTransferRegAlert: "Domain can't be transferred within 60 days of registration. Please wait for 60 days and try again.",
	success_Site_DomainTransferSixtydaysAlert: "A domain cannot be transferred with in 60 days of registration. Please try again after the appropriate amount of time has passed.",
	success_Site_DomainUnLocked: "Domain unlocked successfully.",
	success_Site_FreeDnsAuthEmailSavedSuccessMessage: "New Authorization Email saved successfully",
	success_Site_IPSTagChanged: "The IPS tag will be updated within 24 hours. Once that is done, the domain will immediately be transferred out of Namecheap.",
	success_Site_ParkingPageTurnOn: "Your Parking Page has been turned on.",
	success_Site_Permission_AddSuccessMessage: "The process to grant access rights has been successfully initiated.",
	success_Site_Permission_UpdateSuccessMessage: "User access rights have been successfully updated.",
	success_Site_RedirectDomain: "Redirect domain successfully",
	success_Site_ResendEmailSuccessMessage: "Resending started.",
	success_Site_RightsInvitationAccepted: "The access rights invitation has been accepted.",
	success_Site_SaveAddCategoryMessage: "{Category} assigned to selected domains.",
	success_Site_SaveAutoRenewOffMessage: "Auto-renewal turned OFF.",
	success_Site_SaveAutoRenewOnMessage: "Auto-renewal turned ON.",
	success_Site_SentEmailSuccessStatus: "The Auth Code has been emailed to {emailaddress}.",
	success_Site_SyncMessage: "Sync in progress. {[successcount]} / {[totalcount]} items completed.",
	success_site_updateContactWithoutWGEmail: "Domain contacts updated. WhoisGuard email address unchanged.",
	success_site_updateContactWithWGEmail: "Domain contacts updated. Note: WhoisGuard email address also changed.",
	success_Site_UpdatePushStatus: "Domain ownership change {0} successfully.",
	success_site_updateRegContactExistingDomain: "Your Registrant contact RAA validation is pending. You must complete RAA validation within the next 7 days in order to keep the domain active. <a href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/9305/5/new-icann-whois-validation-process\">Learn More \u2013></a>",
	success_site_updateRegContactNewDomain: "Your Registrant contact RAA validation is pending. You must complete RAA validation within the next 15 days in order to use your domain. <a href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/9305/5/new-icann-whois-validation-process\"> Learn More \u2013></a>",
	success_Site_UpdateRightsStatus: "Domain access rights invitation {0} successfully.",
	success_TurnedOffParkingPage: "You have successfully turned off Parking Page.",
	sucess_Site_ContactUpdate: "Domain contacts updated.",
	tooltip_DomainRedirect: "What is this? <a  target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/384/77/what-is-url-forwarding-and-how-does-it-work\">Learn More &rarr;</a>",
	tooltip_EamilRedirect: "What does this do? <a  target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/308/77/how-to-setup-email-forwarding\">Learn More &rarr;</a>",
	tooltip_NameServers: "<a  target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/9434/32/using-default-nameservers-vs-hosting-nameservers\">Learn more about nameservers</a> or \r\n<a target=\"_blank\" href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/767/10/how-can-i-change-the-nameservers-for-my-domain\">get tips on updating.</a>",
	tooltip_PremiumDNSTooltipBuyed: "You have a PremiumDNS subscription associated to this domain. Here you can enable PremiumDNS on the domain and extend the subscription as needed. <a target='_blank' href=\"https://www.namecheap.com/support/knowledgebase/subcategory.aspx/2231/premiumdns\">Learn more about PremiumDNS.</a>",
	tooltip_PremiumDNSTooltipNotBuyed: "This PremiumDNS subscription needs to be associated to a Domain. <a target='_blank' href=\"https://www.namecheap.com/support/knowledgebase/subcategory.aspx/2231/premiumdns\">Learn more about PremiumDNS.</a>",
	tooltip_ValidityIsNameCheapDomain: "Validity is the period between registration/transfer and expiration.",
	tooltip_ValidityIsNotNameCheapDomain: "Validity is period of time on Whois. This info comes from Whois and may or may not be accurate.",
	tooltip_Whoisguard: "What is this?  <a href=\"https://www.namecheap.com/support/knowledgebase/article.aspx/278/37/what-is-whoisguard\" target=\"_blank\">Learn More &rarr;</a>"
};
